version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: code-reviewer-db
    restart: always
    ports:
    - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: name
      POSTGRES_PASSWORD: password
      POSTGRES_DB: code_reviewer
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
